import '../models/book.dart';

final List<Book> bookList = [
  Book(
    title: "Anatomía y Fisiología",
    author: "Varios",
    price: 19.99,
    image: "assets/images/Anatomia.jpg",
    description: "MEDICINA",
    url: "https://cbtis54.edu.mx/wp-content/uploads/2024/04/Principios-de-Anatomia-y-Fisiologia-Tortora-Derrickson.pdf",
  ),
  Book(
    title: "Asociación Europea de Urología Guía de Bolsillo",
    author: "Juan Manuel Figueroa Ruiz",
    price: 15.00,
    image: "assets/images/Asociación Europea de Urología Guía de Bolsillo.jpg",
    description: "MEDICINA",
    url: "https://www.aeu.es/userfiles/guias_bolsillo_aue.pdf",
  ),
  Book(
    title: "Cardiología en la práctica clínica Tomo 1",
    author: "Lorena Monserrat Angulo Ceballos",
    price: 18.00,
    image: "assets/images/Cardiología en la práctica clínica Tomo 1.jpg",
    description: "MEDICINA",
    url: "https://cuevaseditores.com/libros/Cardiologiaenlapracticaclinicatomo1.pdf",
  ),
  Book(
    title: "Cardiología Fundamental",
    author: "Erik Hugo Zambrano Franco",
    price: 16.00,
    image: "assets/images/Cardiología Fundamental.jpg",
    description: "MEDICINA",
    url: "https://mawil.us/wp-content/uploads/2020/03/cardiologia-fundamental.pdf.pdf",
  ),
  Book(
    title: "Cardiología hoy 2022",
    author: "Elena Días Peláez",
    price: 17.50,
    image: "assets/images/Cardiología hoy 2022.jpg",
    description: "MEDICINA",
    url: "https://secardiologia.es/images/publicaciones/libros/ebook-cardiologia-hoy-2022.pdf",
  ),
  Book(
    title: "Curso Básico Sistema de Comandos de Incidentes",
    author: "América y el Caribe",
    price: 13.50,
    image: "assets/images/Curso Básico Sistema de Comandos de Incidentes.jpg",
    description: "MEDICINA",
    url: "https://www.gob.mx/cms/uploads/attachment/file/228836/Curso_Basico_SCI_material_de_referencia.pdf",
  ),
  Book(
    title: "Fundamentos de Nefrología Clínica",
    author: "Andres Enrique Pluas Alvario",
    price: 18.50,
    image: "assets/images/Fundamentos de Nefrología Clínica.jpg",
    description: "MEDICINA",
    url: "https://cuevaseditores.com/libros/2025/marzo/nefrologiaclinica.pdf",
  ),
  Book(
    title: "Guía didactica curso del curso básico Sistema de comando de incidentes",
    author: "Ligia Gabriela Alburez Mendieta",
    price: 12.00,
    image: "assets/images/Guía didactica curso del curso básico Sistema de comando de incidentes.jpg",
    description: "MEDICINA",
    url: "https://conred.gob.gt/documentos/guias/Guia_didactica_curso_basico_SCI.pdf",
  ),
  Book(
    title: "Guía para el diagnóstico y tratamiento del ictus",
    author: "E. Díez Tejedor",
    price: 14.50,
    image: "assets/images/Guía para el diagnóstico y tratamiento del ictus.jpg",
    description: "MEDICINA",
    url: "https://www.sen.es/pdf/guias/Guia_oficial_para_el_diagnostico_y_tratamiento_del_ictus_2006.pdf",
  ),
  Book(
    title: "Guía sobre accidentes Cerebrovasculares",
    author: "Varios",
    price: 15.00,
    image: "assets/images/Guía sobre accidentes Cerebrovasculares.jpg",
    description: "MEDICINA",
    url: "https://www.med.unc.edu/neurology/wp-content/uploads/sites/716/2018/05/overview-of-stroke-for-patients-and-caregivers-spanish.pdf",
  ),
  Book(
    title: "INTRODUCCIÓN A LA CARDIOLOGÍA",
    author: "Dra. Mayra Elizabeth Jiménez Capa Esp.",
    price: 16.00,
    image: "assets/images/INTRODUCCIÓN A LA CARDIOLOGÍA.jpg",
    description: "MEDICINA",
    url: "https://mawil.us/wp-content/uploads/2019/11/introduccion-a-la-cardiologia.pdf",
  ),
  Book(
    title: "Libro guía del residente de Cardiología",
    author: "Joan Antoni Gómez Hospital",
    price: 16.50,
    image: "assets/images/Libro guía del residente de Cardiología.jpg",
    description: "MEDICINA",
    url: "https://secardiologia.es/images/publicaciones/libros/2007-sec-monografia-residentes.pdf",
  ),
  Book(
    title: "Manual de obstetricia",
    author: "DR. JORGE CARVAJAL DRA. KAREN F. GARCIA A.",
    price: 19.50,
    image: "assets/images/Manual de obstetricia.jpg",
    description: "MEDICINA",
    url: "https://medicina.uc.cl/wp-content/uploads/2024/03/Manual-Obstetricia-y-Ginecologia-2024_compressed.pdf",
  ),
  Book(
    title: "Medicina General Integral",
    author: "Varios",
    price: 19.99,
    image: "assets/images/Medicina General Integral.jpg",
    description: "MEDICINA",
    url: "https://fundacionortizavila.com/descargar/338/045e439a866e0a2c0c7b004ef836c415",
  ),
  Book(
    title: "Medicina Interna",
    author: "Vallejo Zambrano",
    price: 19.50,
    image: "assets/images/Medicina Interna.jpg",
    description: "MEDICINA",
    url: "https://mawil.us/wp-content/uploads/2021/09/principios-basicos-de-medicina-interna.pdf",
  ),
  Book(
    title: "Neurofisiologia Esencial",
    author: "Granada",
    price: 17.00,
    image: "assets/images/Neurofisiologia Esencial.jpg",
    description: "MEDICINA",
    url: "https://editorial.ugr.es/media/ugr/files/sample-137770.pdf",
  ),
  Book(
    title: "Obstetricia y ginecologia",
    author: "Beckmann y Ling",
    price: 19.00,
    image: "assets/images/Obstetricia y ginecologia.jpg",
    description: "MEDICINA",
    url: "https://sncpharma.com/wp-content/uploads/2021/01/Beckmann-y-Ling.-Obstetricia-y-ginecolog%C3%ADa-Spanish-Edition.pdf",
  ),
  Book(
    title: "Propedeutica Clinica",
    author: "Varios",
    price: 18.50,
    image: "assets/images/Propedeutica Clinica.jpeg",
    description: "MEDICINA",
    url: "https://joseluisvitte.wordpress.com/wp-content/uploads/2019/07/propedeutica-clinica-y-semiologia-medica-tomo-i.pdf",
  ),
  Book(
    title: "Urgencias Urológicas",
    author: "Dr. Leonardo Perroni Artola",
    price: 17.00,
    image: "assets/images/Urgencias Urológicas.jpg",
    description: "MEDICINA",
    url: "https://catedradeurologia.edu.uy/wp-content/uploads/2016/12/libro-emergencias-urologicas.pdf",
  ),
];
